### ISSUE TITLE
Error on startup (first window) without an internet connection

### ISSUE THREAD

**Issue by ikirill** [yishn/Sabaki#211]
If I open the last release of Sabaki (0.30.2) on my OSX, without having an internet connection, I get the following error displayed in a dialog box (no output on stderr). There is no error if I have an internet connection. This seems to only happen on the first window that gets opened by default, I can still interact with Sabaki.

    TypeError: Cannot match against 'undefined' or 'null'.
        at EventEmitter.ipcMain.once (/Users/kirill/Sandboxes/Games/Sabaki.app/Contents/Resources/app.asar/main.js:113:34)
        at Object.onceWrapper (events.js:290:19)
        at emitTwo (events.js:106:13)
        at EventEmitter.emit (events.js:191:7)
        at WebContents.<anonymous> (/Users/kirill/Sandboxes/Games/Sabaki.app/Contents/Resources/electron.asar/browser/api/web-contents.js:247:37)
        at emitTwo (events.js:106:13)
        at WebContents.emit (events.js:191:7)

It's the pattern match here: https://github.com/yishn/Sabaki/blob/master/main.js#L113

**Comment by Seth-Rothschild** [comment]
This is "check for updates at startup" in preferences. If you uncheck it the error will disappear. 

Maybe update check should have different behavior, but for now that should solve your problem.
